[project]
name = ComfyUI-Apt_Preset""
description = ""
version = "1.0.0"
license = "LICENSE"

[project.urls]
Repository = "https://github.com/cardenluo/ComfyUI-Apt_Preset.git"


[tool.comfy]
PublisherId = "cardenluo"
DisplayName = "ComfyUI-Apt_Preset"
Icon = ""
