run_Mode = "FLUX"
ckpt_name = "None"
clipnum = 0
unet_name = "hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors"
clip1 = "clip_l.safetensors"
clip2 = "llava_llama3_fp8_scaled.safetensors"
clip_type = "hunyuan_video"
clip3 = "None"
unet_Weight_Dtype = "fp8_e4m3fn"
vae= "hunyuan_video_vae_bf16.safetensors"
lora = "None"
strength = "1.0"
width = 848
height = 480
batch = 1
steps = 20
cfg = 1.0
sampler = "euler"
scheduler = "simple"
guidance = "6.0"
positive = "a girl,sea"
negative = ""
