run_Mode = "FLUX"
ckpt_name = "None"
clipnum = -2
unet_name = "fluxFillFP8_v10.safetensors"
clip1 = "clip_l.safetensors"
clip2 = "t5xxl_fp8_e4m3fn.safetensors"
clip_type = "flux"
clip3 = "None"
unet_Weight_Dtype = "fp8_e4m3fn"
vae = "ae.safetensors"
lora = "None"
strength = "1.0"
width = 1024
height = 1024
batch = 1
steps = 30
cfg = 1.0
sampler = "euler"
scheduler = "normal"
guidance = "30.0"
