text = ""
positive= "A pattern made up of [many noodles] that resembles a human figure. The outline is quite clear and the texture of [the noodles] can be seen in the details. The overall effect is both creative and playful."
negative= ""