text = ""
positive= "(((the [water] is morphing and taking shape of a [object], the [water] should have detailed defined texture and natural colour, their movement recreating mesmerizing trails of light)))"
negative= ""