control = "XL-diffusers_canny_full.safetensors"
strength1 = 0.5
start_percen1 = 0
end_percen1 = 0.8
contro2 = "XL-thibaud_xl_openpose.safetensors"
strength2 = 0.5
start_percen2 = 0
end_percen2 = 0.8
contro3 = "XL-sai_xl_depth_.safetensors"
strength3 = 0.5
start_percen3 = 0
end_percen3 = 0.8
contro4 = "XL-xinsir-scribble-1.0.safetensors"
strength4 = 0.5
start_percen4 = 0
end_percen4 = 0.8
