run_Mode = "clip"
ckpt_name = "ltx-video-2b-v0.9.safetensors"
clipnum = "-2"
unet_name = "None"
unet_Weight_Dtype = "None"
clip_type = "ltxv"
clip1 = "t5xxl_fp8_e4m3fn.safetensors"
clip2 = "None"
guidance = "3.5"
clip3 = "None"
vae = "None"
lora = "None"
lora_strength = "1.0"
width = "512"
height = "512"
batch = "1"
steps = "20"
cfg = "8.0"
sampler = "euler"
scheduler = "normal"
