run_Mode = "None"
ckpt_name = "None"
clipnum = "-2"
unet_name = "hidream_i1_fast_fp8.safetensors"
unet_Weight_Dtype = "default"
clip_type = "None"
clip1 = "clip_l_hidream.safetensors"
clip2 = "clip_g_hidream.safetensors"
guidance = "3.5"
clip3 = "t5xxl_fp8_e4m3fn_scaled.safetensors"
clip4 = "llama_3.1_8b_instruct_fp8_scaled.safetensors"
vae = "ae.safetensors"
lora = "None"
lora_strength = "1.0"
width = "1024"
height = "1024"
batch = "1"
steps = "10"
cfg = "5.0"
sampler = "uni_pc"
scheduler = "simple"
positive = "beautiful detailed glow,a girl"
negative= "worst quality, low quality"
cache_threshold = "0.0"
attention = "nunchaku-fp16"
cpu_offload = "auto"
device_id = "0"
data_type = "bfloat16"
i2f_mode = "enabled"