run_Mode = "None"
ckpt_name = "None"
clipnum = "-2"
unet_name = "GGUF\\qwen-image-Q6_K.gguf"
unet_Weight_Dtype = "None"
clip_type = "qwen_image"
clip1 = "qwen_2.5_vl_7b.safetensors"
clip2 = "None"
guidance = "3.5"
clip3 = "None"
clip4 = "None"
vae = "qwen_image_vae.safetensors"
lora = "None"
lora_strength = "1.0"
width = "1024"
height = "1024"
batch = "1"
steps = "20"
cfg = "4.0"
sampler = "euler"
scheduler = "normal"
positive = "beautiful detailed glow,a girl"
negative= "worst quality, low quality"
