run_Mode = "None"
ckpt_name = "None"
clipnum = "-2"
unet_name = "GGUF\\Qwen_Image_Edit-Q4_K_S.gguf"
unet_Weight_Dtype = "None"
clip_type = "qwen_image"
clip1 = "qwen_2.5_vl_7b_fp8_scaled.safetensors"
clip2 = "None"
guidance = "3.5"
clip3 = "None"
clip4 = "None"
vae = "qwen_image_vae.safetensors"
lora = "qwen\\Qwen-Image-Lightning-4steps-V1.0.safetensors"
lora_strength = "1.0"
width = "1024"
height = "1024"
batch = "1"
steps = "5"
cfg = "1.0"
sampler = "euler"
scheduler = "normal"
positive = "beautiful detailed glow,a girl"
negative= "worst quality, low quality"
