run_Mode = "None"
ckpt_name = "None"
clipnum = "-2"
unet_name = "wan2.2\\Wan2.2-T2V-A14B-HighNoise-Q6_K.gguf"
unet_Weight_Dtype = "default"
clip_type = "wan"
clip1 = "umt5_xxl_fp8_e4m3fn_scaled.safetensors"
clip2 = "None"
guidance = "3.5"
clip3 = "None"
clip4 = "None"
vae = "wan_2.1_vae.safetensors"
lora = "Wan2.2\\Wan2.2-Lightning_I2V-A14B-4steps-lora_HIGH_fp16.safetensors"
lora_strength = "0.75"
width = "1280"
height = "720"
batch = "1"
steps = "8"
cfg = "1.0"
sampler = "uni_pc"
scheduler = "simple"
positive = "beautiful detailed glow,a girl"
negative= "色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走"
