run_Mode = "FLUX"
ckpt_name = "None"
clipnum = "None"
unet_name = "svdq-int4_r32-flux.1-kontext-dev.safetensors"
unet_Weight_Dtype = "None"
clip_type = "None"
clip1 = "clip_l.safetensors"
clip2 = "t5xxl_fp8_e4m3fn.safetensors"
guidance = 3.5
clip3 = "None"
clip4 = "None"
vae = "ae.safetensors"
lora = "None"
lora_strength = 1.0
width = 1024
height = 1024
batch = 1
steps = 10
cfg = 1.0
sampler = "euler"
scheduler = "simple"
positive = "beautiful detailed glow,a girl"
negative = "worst quality, low quality"
cache_threshold = 0.0
attention = "nunchaku-fp16"
cpu_offload = "auto"
