run_Mode = "basic"
ckpt_name = "AA\\majicMIX realistic _v1.safetensors"
clipnum = -2
vae = "A-840000-ema-pruned-real.pt"
PromptLora = "<lora:LCM/AnimateLCM_sd15_t2v_lora.safetensors:1.0>"
PromptMid = "a girl ,garden ,flowers"

width = "512"
height = "768"
batch = "1"
steps = "8"
cfg = "2.5"
sampler = "lcm"
scheduler = "normal"
lora ="LCM\\AnimateLCM_sd15_t2v_lora.safetensors"
lora_strength = 1.0
unet_name="None"
clip1="None"
clip2="None"
clip3="None"
unet_Weight_Dtype="None"
cache_threshold = "0.0"
attention = "nunchaku-fp16"
cpu_offload = "auto"