run_Mode = "basic"
ckpt_name = "SD3.5\\sd3.5_large_fp8_scaled.safetensors"
clipnum = "0"
vae = "SD3.5vae.safetensors"
PromptLora = ""
PromptMid = "a girl ,garden ,flowers"

width = 1024
height = 1024
batch = 1
steps = 20
cfg = 4.0
sampler = "dpmpp_2m"
scheduler = "sgm_uniform"

lora ="None"
lora_strength = 1.0
unet_name="None"
clip1="None"
clip2="None"
clip3="None"
unet_Weight_Dtype="None"