run_Mode = "None"
ckpt_name = "SDXL\\XL_fantasy.safetensors"
clipnum = -2
unet_name = "None"
unet_Weight_Dtype = "None"
clip_type = "None"
clip1 = "None"
clip2 = "None"
guidance = 3.5
clip3 = "None"
clip4 = "None"
vae = "sdxl_vae.safetensors"
lora = "None"
lora_strength = 1.0
width = 1024
height = 1024
batch = 1
steps = 20
cfg = 8.0
sampler = "euler"
scheduler = "normal"
positive = "beautiful detailed glow,a girl"
negative = "worst quality, low quality"
cache_threshold = "None"
attention = "None"
cpu_offload = "None"
