run_Mode = "basic"
ckpt_name = "AA\\majicMIX realistic _v1.safetensors"
clipnum = "-2"
unet_name = "None"
unet_Weight_Dtype = "None"
clip_type = "None"
clip1 = "None"
clip2 = "None"
guidance = "1.0"
clip3 = "None"
vae = "A-840000-ema-pruned-real.pt"
lora = "LCM\\AnimateLCM_sd15_t2v_lora.safetensors"
lora_strength = "1.0"
width = "512"
height = "768"
batch = "1"
steps = "8"
cfg = "2.5"
sampler = "lcm"
scheduler = "karras"
positive = "beautiful detailed glow,a girl"
negative= "worst quality, low quality"
