run_Mode = "basic"
ckpt_name = "SDXL\\XL_fantasy.safetensors"
clipnum = "-2"
vae = "sdxl_vae.safetensors"
PromptLora = "<lora:Hyper-SD/Hyper-SDXL-2steps-lora.safetensors:1.0>"
PromptMid = "a girl ,garden ,flowers"
NegPrompt = ""
PromptBack = ""
width = 1024
height = 1024
batch = 1
steps = 5
cfg = 1
sampler = "euler_ancestral_cfg_pp"
scheduler = "normal"
seedflow= 3
lora ="Hyper-SD\\Hyper-SDXL-2steps-lora.safetensors"
lora_strength = 1.0
unet_name="None"
clip1="None"
clip2="None"
clip3="None"
unet_Weight_Dtype="None"