run_Mode = "only_clip"
ckpt_name = "None"
clipnum = "0"
unet_name = "None"
unet_Weight_Dtype = "None"
clip_type = "hunyuan_video"
clip1 = "clip_l.safetensors"
clip2 = "llava_llama3_fp8_scaled.safetensors"
guidance = "30.0"
clip3 = "None"
vae = "hunyuan_video_vae_bf16.safetensors"
lora = "None"
lora_strength = "1.0"
width = "512"
height = "768"
batch = "1"
steps = "24"
cfg = "1.0"
sampler = "uni_pc"
scheduler = "normal"
positive = "a girl,sea"
negative= "worst quality, low quality"
