run_Mode = "clip"
ckpt_name = "None"
clipnum = "0"
unet_name = "Wan2.1-Fun-1.3B-InP.safetensors"
unet_Weight_Dtype = "default"
clip_type = "wan"
clip1 = "umt5_xxl_fp8_e4m3fn_scaled.safetensors"
clip2 = "None"
guidance = "3.5"
clip3 = "None"
vae = "wan_2.1_vae.safetensors"
lora = "None"
lora_strength = "1.0"
width = "1024"
height = "1024"
batch = "1"
steps = "20"
cfg = "6.0"
sampler = "uni_pc"
scheduler = "simple"
positive = "a girl,sea"
negative= "worst quality, low quality"
