control = "Flux.1-dev-ControlNet-Union-Pro-fp8.safetensors"
strength1 = 0.5
start_percen1 = 0
end_percen1 = 0.8
contro2 = "Flux.1-dev-ControlNet-Union-Pro-fp8.safetensors"
strength2 = 0.5
start_percen2 = 0
end_percen2 = 0.8
contro3 = "Flux.1-dev-ControlNet-Union-Pro-fp8.safetensors"
strength3 = 0.5
start_percen3 = 0
end_percen3 = 0.8
contro4 = "Flux.1-dev-Controlnet-Upscaler.safetensors"
strength4 = 0.5
start_percen4 = 0
end_percen4 = 0.8







