control = "control_v11p_sd15_canny.pth"
strength1 = 0.5
start_percen1 = 0
end_percen1 = 0.8
contro2 = "control_v11p_sd15_openpose.pth"
strength2 = 0.5
start_percen2 = 0
end_percen2 = 0.8
contro3 = "control_v11f1p_sd15_depth.pth"
strength3 = 0.5
start_percen3 = 0
end_percen3 = 0.8
contro4 = "control_v11p_sd15_scribble.pth"
strength4 = 0.5
start_percen4 = 0
end_percen4 = 0.8






