control = "sd3.5_large_controlnet_canny.safetensors"
strength1 = 0.5
start_percen1 = 0
end_percen1 = 0.8
contro2 = "None"
strength2 = 0.5
start_percen2 = 0
end_percen2 = 0.8
contro3 = "sd3.5_large_controlnet_depth.safetensors"
strength3 = 0.5
start_percen3 = 0
end_percen3 = 0.8
contro4 = "sd3.5_large_controlnet_blur.safetensors"
strength4 = 0.5
start_percen4 = 0
end_percen4 = 0.8






