control = "None"
strength1 = 0.5
start_percen1 = 0
end_percen1 = 0.8
contro2 = "None"
strength2 = 0.5
start_percen2 = 0
end_percen2 = 0.8
contro3 = "None"
strength3 = 0.5
start_percen3 = 0
end_percen3 = 0.8
contro4 = "None"
strength4 = 0.5
start_percen4 = 0
end_percen4 = 0.8
