run_Mode = "FLUX"
ckpt_name = "None"
clipnum = "0"
unet_name = "Flex.2-preview.safetensors"
unet_Weight_Dtype = "fp8_e4m3fn"
clip_type = "flux"
clip1 = "clip_l.safetensors"
clip2 = "t5xxl_fp8_e4m3fn.safetensors"
guidance = "3.5"
clip3 = "None"
vae = "ae.safetensors"
lora = "None"
lora_strength = "1.0"
width = "1024"
height = "1024"
batch = "1"
steps = "20"
cfg = "1.0"
sampler = "euler"
scheduler = "normal"
positive = "a girl,sea"
negative= "worst quality, low quality"
cache_threshold = "0.0"
attention = "nunchaku-fp16"
cpu_offload = "auto"