run_Mode = "FLUX"
ckpt_name = "None"
clipnum = "-2"
unet_name = "skyreels_hunyuan_i2v_fp8_e4m3fn.safetensors"
unet_Weight_Dtype = "fp8_e4m3fn_fast"
clip_type = "hunyuan_video"
clip1 = "clip_l.safetensors"
clip2 = "llava_llama3_fp8_scaled.safetensors"
guidance = "1.0"
clip3 = "None"
vae = "hunyuan_video_vae_bf16.safetensors"
lora = "hunyuan\\skyreels-i2v-smooth-lora-test-00000350.safetensors"
lora_strength = "1.0"
width = "544"
height = "544"
batch = "1"
steps = "10"
cfg = "8.0"
sampler = "euler"
scheduler = "simple"
cache_threshold = "0.0"
attention = "nunchaku-fp16"
cpu_offload = "auto"