run_Mode = "None"
ckpt_name = "None"
clipnum = "-2"
unet_name = "GGUF\\flux1-fill-dev-fp16-Q8_0-GGUF.gguf"
unet_Weight_Dtype = "fp8_e4m3fn"
clip_type = "flux"
clip1 = "clip_l.safetensors"
clip2 = "t5xxl_fp8_e4m3fn.safetensors"
guidance = "30.0"
clip3 = "None"
clip4 = "None"
vae = "ae.safetensors"
lora = "Flux_function\\removal-v2.safetensors"
lora_strength = "1.0"
width = "1024"
height = "1024"
batch = "1"
steps = "20"
cfg = "1.0"
sampler = "euler"
scheduler = "normal"
positive = "beautiful detailed glow,a girl"
negative= "worst quality, low quality"
