run_Mode = "basic"
ckpt_name = "AA\\majicMIX realistic _v1.safetensors"
clipnum = "-2"
unet_name = "None"
unet_Weight_Dtype = "None"
clip_type = "None"
clip1 = "None"
clip2 = "None"
guidance = "3.5"
clip3 = "None"
vae = "A-840000-ema-pruned-real.pt"
lora = "ACG\\comfyui_local_lora16.safetensors"
lora_strength = "1.0"
width = "512"
height = "512"
batch = "1"
steps = "20"
cfg = "8.0"
sampler = "euler"
scheduler = "normal"
